### ISSUE TITLE
expects_obj ImportError from argh (recently deprecated)

### ISSUE THREAD

**Issue by noische** [season-framework/dizest#8]
I'm trying to install dizest on Ubuntu machine and the following is the error message I got:

$ dizest install codes/dizest
Traceback (most recent call last):
  File "/home/noische/.local/bin/dizest", line 5, in <module>
    from dizest.cmd import main
  File "/home/noische/.local/lib/python3.10/site-packages/dizest/cmd.py", line 10, in <module>
    from .command.run import run, server, kill
  File "/home/noische/.local/lib/python3.10/site-packages/dizest/command/run.py", line 3, in <module>
    from argh import arg, expects_obj
ImportError: cannot import name 'expects_obj' from 'argh' (/home/noische/.local/lib/python3.10/site-packages/argh/__init__.py)

It seems that the latest argh 0.31.2 has removed expects_obj().
dizest install works fine with argh==0.30.5

**Comment by proin** [comment]
We have updated the code to be compatible with the latest version of argh. The issue you’re encountering stems from changes in argh version 0.31.2, which removed the expects_obj() function. Please try using the updated version of dizest, which should now work with the latest argh. Let us know if you encounter any further issues.
